#!/bin/bash
# Measure a query, apply the fix the diagnostics point to, measure again. Writes results/tuning.md.
set -euo pipefail
Q="select c.country, count(*) as orders, sum(o.total_cents) as cents
   from customers c join orders o on o.customer_id = c.customer_id
   where c.country = 'CA' and o.placed_at >= now() - interval '90 days'
   group by 1"
Q2="select * from orders where customer_id = 12345 order by placed_at desc limit 20"

run() { psql -U postgres -d appdb -tAc "$1"; }
plan() { psql -U postgres -d appdb -Xc "explain (analyze, buffers, timing off, summary on) $2" | sed 's/^/    /'; }

mkdir -p /results
{
  echo "# Tuning demo"
  echo
  echo "Generated by scripts/tuning_demo.sh on \$(date -u +%Y-%m-%dT%H:%M:%SZ). 1,000,000 orders, 200,000 customers."
  echo
  echo "## The diagnostic that found it"
  echo
  echo "\`sql/03_indexing.sql\` lists foreign keys with no supporting index:"
  echo
  echo '```'
  psql -U postgres -d appdb -Xf /sql/03_indexing.sql 2>/dev/null | sed -n '/foreign keys with no/,/^$/p'
  echo '```'
  echo
  echo "## Query 1: recent orders for one customer"
  echo
  echo '```sql'; echo "$Q2"; echo '```'
  echo
  echo "### Before"
  echo '```'; plan "" "$Q2"; echo '```'
} > /results/tuning.md

# Execution time straight out of the JSON plan, via SQL rather than a JSON tool the image may not have.
measure() {  # $1 = query -> execution time in ms from the JSON plan
  psql -U postgres -d appdb -tAX -c "explain (analyze, format json) $1" | tr -d '\n' > /tmp/plan.json
  awk -F'"Execution Time": ' '{print $2}' /tmp/plan.json | tr -d ' }]' | head -1
}

BEFORE2=$(measure "$Q2")
BEFORE1=$(measure "$Q")

psql -U postgres -d appdb -c "create index concurrently if not exists ix_orders_customer_placed on orders(customer_id, placed_at desc)" >/dev/null
psql -U postgres -d appdb -c "create index concurrently if not exists ix_customers_country on customers(country)" >/dev/null
psql -U postgres -d appdb -c "create index concurrently if not exists ix_orders_placed_at on orders(placed_at)" >/dev/null
psql -U postgres -d appdb -c "analyze orders; analyze customers;" >/dev/null

AFTER2=$(measure "$Q2")
AFTER1=$(measure "$Q")

{
  echo
  echo "### After \`create index concurrently ix_orders_customer_placed on orders(customer_id, placed_at desc)\`"
  echo '```'; plan "" "$Q2"; echo '```'
  echo
  echo "## Query 2: 90-day order summary for one country"
  echo
  echo '```sql'; echo "$Q"; echo '```'
  echo
  echo "### After indexing customers(country) and orders(placed_at)"
  echo '```'; plan "" "$Q"; echo '```'
  echo
  echo "## Result"
  echo
  echo "| query | before (ms) | after (ms) | change |"
  echo "|---|---:|---:|---:|"
  awk -v b2="$BEFORE2" -v a2="$AFTER2" -v b1="$BEFORE1" -v a1="$AFTER1" 'BEGIN{
    printf "| recent orders for one customer | %.1f | %.1f | %.0fx faster |\n", b2, a2, b2/a2;
    printf "| 90-day summary for one country | %.1f | %.1f | %.1fx faster |\n", b1, a1, b1/a1;
  }' 
  echo
  echo "\`create index concurrently\` was used so the table is never locked against writes - the difference between"
  echo "a maintenance window and a transparent change on a production system."
} >> /results/tuning.md
echo "wrote results/tuning.md"
